### ISSUE TITLE
one liner is incorrect

### ISSUE THREAD

**Issue by btopro** [bradallenfisher/php-fpm-apache-2.4-centos7#1]
should be:
`yes | yum -y install git && git clone https://github.com/bradallenfisher/php-fpm-apache-2.4-centos7.git && cd php-fpm-apache-2.4-centos7/install && chmod 700 prod.sh && ./prod.sh`

**Comment by baf139** [comment]
changed one liner back to the root directory. if in install directory the other directories are not relative. might be why you had issue with this.
